-- Copia y pega esto en el 'SQL Editor' de tu panel de Supabase
-- Esto creará la tabla donde se guardarán los clientes

create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  intent text,
  phone text,
  source text,
  type text,
  location text,
  specs text,
  garage text,
  appraisal text
);

-- Habilitar acceso público (para este prototipo)
-- IMPORTANTE: Esto permite que cualquiera pueda leer/escribir. 
-- Para producción real, deberíamos configurar 'RLS Policies'.

alter table leads enable row level security;

create policy "Public Access"
on leads
for all
using (true)
with check (true);
